USE Proyecto_Final;

INSERT INTO Perfiles (nombre) VALUES
('Profesorado'),
('Direccion');
SELECT * FROM Perfiles;

INSERT INTO Profesores (
    dni,
    nombre,
    apellidos,
    email,
    password,
    puntos_guardia,
    id_perfil_profesores
) VALUES (
    '00000000A',
    'Root',
    'Administrador',
    'root@guardias.com',
    'scrypt:32768:8:1$lm08SFbcHkwhpk1z$5bf2992cad239243d00d502289ec68001ff794511d10d4cab210a5da8e4dabd0230fc73bd4f41d8cd15701e21ba76f660db96f9e25c1f5b38476d3b2ab12202b',
    0,
    2
);

INSERT INTO Grupos (nombre) VALUES
('ESO 1ª A'),
('ESO 1ª B'),
('ESO 1ª C'),
('ESO 1ª D'),
('ESO 1ª E'),
('ESO 2ª A'),
('ESO 2ª B'),
('ESO 2ª C'),
('ESO 2ª D'),
('ESO 2ª E'),
('ESO 2ª F'),
('ESO 3ª A'),
('ESO 3ª B'),
('ESO 3ª C'),
('ESO 3ª D'),
('ESO 3ª E'),
('ESO 4ª A'),
('ESO 4ª B'),
('ESO 4ª C'),
('ESO 4ª D'),
('ESO 4ª E'),
('BACH 1º A Ciencias y Tecnología'),
('BACH 1º B Ciencias y Tecnología'),
('BACH 1º C Ciencias y Tecnología'),
('BACH 2º A Ciencias y Tecnología'),
('BACH 2º B Ciencias y Tecnología'),
('BACH 2º C Ciencias y Tecnología'),
('BACH 1º A Humanidades y Ciencias Sociales'),
('BACH 1º B Humanidades y Ciencias Sociales'),
('BACH 1º C Humanidades y Ciencias Sociales'),
('BACH 2º A Humanidades y Ciencias Sociales'),
('BACH 2º B Humanidades y Ciencias Sociales'),
('BACH 2º C Humanidades y Ciencias Sociales'),
('1º SMR'),
('2º SMR'),
('1º ASIR'),
('2º ASIR'),
('1º IC'),
('2º IC');

INSERT INTO Dias_Semana (nombre) VALUES
('Lunes'),
('Martes'),
('Miércoles'),
('Jueves'),
('Viernes');

INSERT INTO Tramos_Horarios (horario) VALUES
('08:15 - 09:15'),
('09:15 - 10:15'),
('10:15 - 11:15'),
('11:15 - 11:45'),
('11:45 - 12:45'),
('12:45 - 13:45'),
('13:45 - 14:45');
SELECT * FROM Asignaturas;
INSERT INTO Asignaturas (nombre) VALUES
('Administración de Sistema Gestores de Bases de Datos'),
('Ampliación Anatomía'),
('Ambito Cientifico Tecnologico'),
('Ambito Sociolingüístico'),
('Anatomia Aplicada'),
('Apoyo Geografía e Historia'),
('Apoyo Laboratorio Biologia y Geología'),
('Apoyo Laboratorio Biologico'),
('Apoyo Laboratorio Fisica y Química'),
('Apoyo Lengua'),
('Aplicaciones Ofimáticas'),
('Aplicaciones Ofimáticas Desdoble 1 hora'),
('Aplicaciones Ofimáticas desdoble 3 horas'),
('Aplicaciones Web'),
('Aplicaciones Web desdoble 2 horas'),
('Atención Educativa'),
('Biología'),
('Biología y Geología'),
('Ciencias Aplicadas'),
('Ciencias Aplicadas 1º'),
('Comentario de Texto'),
('Computación y Robótica'),
('Comunicación y Sociedad'),
('Cultura Emprendedora'),
('Dibujo Técnico'),
('Digitalización'),
('Educación Física'),
('Educación Física Musical'),
('Educación Plástica'),
('Educación Plastica y Visual'),
('Economía'),
('Economía 1º Bachillerato'),
('Empresa e Iniciativa Emprendedora'),
('Equipo Tecnico de Coordinación Pedagógica'),
('Equipos Eléctricos y Electrónicos'),
('Espresión Artística'),
('Filosofía'),
('Filosofía 1º Bachillerato'),
('Filosofía Musical'),
('Fisica'),
('Fisica y Química'),
('Formación y Orientación Profesional'),
('Francés'),
('Frances 2º Idioma'),
('Frances 4ª'),
('Fundamentos de Hardware'),
('Geografía e Historia'),
('Gestión de Bases de Datos'),
('Griego'),
('Guardia'),
('Guardia Pabellón 2'),
('Guardia Recreo'),
('Horas de Libre Configuración'),
('Historia'),
('Historia de España'),
('Historia del Arte'),
('Historia Musical'),
('Implantación de Aplicaciones Web'),
('Implantación de Sistemas Operativos'),
('Inglés'),
('Ingles 1º'),
('Ingles 2ª + Proyecto'),
('Ingles 2º'),
('Ingles Músical'),
('Instalación y Mantenimiento de Redes de Transmisión de Datos'),
('Itinerario Personal'),
('Lengua'),
('Lengua Castellana'),
('Lengua Castellana y Literatura'),
('Lengua Musical'),
('Lenguajes de Marcas y Sistemas de Gestión de Información'),
('Literatura Universal'),
('Montaje y Mantenimiento'),
('Montaje y Mantenimiento Desdoble'),
('Música'),
('Matemáticas'),
('Matemáticas Académicas'),
('Matemáticas Aplicadas'),
('Matemáticas Ciencias Sociales'),
('Matemáticas Musical'),
('Operaciones Auxiliares para Comercio'),
('Oratoria y Debate'),
('Patrimonio Cultural de Andalucía'),
('Planificación y Administración de Redes'),
('Preparación DELF'),
('Proyecto Educación Valores'),
('Proyecto Educación en Valores'),
('Química'),
('Redes Locales'),
('Redes Locales Desdoble 2 horas'),
('Redes desdoble 1 hora'),
('Religión'),
('Religión Evangélica'),
('Religión Musical'),
('Refuerzo Lengua'),
('Refuerzo de Matemáticas'),
('Reunión'),
('Reunión Departamento'),
('Reunión Evaluación'),
('Reunión Junta Directiva'),
('Reunión Tutores'),
('Servicios de Red e Internet'),
('Servicios de Red e Internet desdoble 3 horas'),
('Servicios en Red'),
('Seguridad Informática'),
('Seguridad y Alta Disponibilidad'),
('Sistema Operativos Monopuestos'),
('Sistemas de Información y Organización desdoble 1 hora'),
('Sistemas Operativos en Red'),
('Sostenibilidad'),
('Taller Cerámica'),
('Tecnología'),
('Tecnología 4º'),
('Tecnología Industrial'),
('Tecnología Musical'),
('Tecnologías de la Información y la Comunicación'),
('TIC'),
('Trinity B1'),
('Tutoría'),
('Tutoría Orientación'),
('Unidad Formativa Prevención de Riesgos Laborales');

INSERT INTO Aulas (nombre) VALUES
('A.10 Aula Multimedia'),
('AULA 1o CFGM'),
('AULA 1o CFGS'),
('AULA 1o FPB'),
('AULA 2o CFGM'),
('AULA 2o CFGS'),
('AULA 2o FPB'),
('Aula 1'),
('Aula 11'),
('Aula 12'),
('Aula 13'),
('Aula 15'),
('Aula 16'),
('Aula 17'),
('Aula 18'),
('Aula 19'),
('Aula 2'),
('Aula 20'),
('Aula 21'),
('Aula 22'),
('Aula 23'),
('Aula 24'),
('Aula 27'),
('Aula 28'),
('Aula 3'),
('Aula 4 PMAR 2o'),
('Aula 5'),
('Aula 6'),
('Aula 7'),
('Aula 8'),
('Aula 9 PMAR 3o'),
('Aula Frances'),
('Aula LABORATORIO QUÍMICA'),
('Aula de Dibujo'),
('Aula de Informática'),
('Aula de Radio'),
('Aula de Tecnología'),
('Aula de clásicas'),
('Aula de música'),
('Aula desdoble'),
('Aulas para desdobles'),
('Biblioteca'),
('Dpto. Geografía e Historia'),
('Laboratorio FyQ'),
('Laboratorio Geología'),
('Laboratorio biología'),
('Patio deportivo'),
('Salón de usos múltiples'),
('Taller Montaje Informática');

/** INSERCCIÓN HORARIOS PRUEBAS **/
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula)
VALUES ('00000000A',1,1,13,16,14);
INSERT INTO Horarios(dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_asignatura_horarios) VALUES ('00000000A',1,2,50);
INSERT INTO Horarios(dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_asignatura_horarios) VALUES ('00000000A',1,3,34);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',1,5,21,77,15);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',1,6,25,80,42);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',2,5,21,77,15);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',2,6,28,76,42);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',2,7,25,80,42);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',3,1,51,47);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',3,2,25,80,42);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',3,3,28,76,42);
INSERT INTO Horarios(dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_asignatura_horarios) VALUES ('00000000A',3,5,50);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',3,6,21,77,15);
INSERT INTO Horarios(dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_asignatura_horarios) VALUES ('00000000A',4,5,98);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',4,6,28,76,42);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',5,1,21,77,15);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',5,2,25,80,42);
INSERT INTO Horarios(dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_asignatura_horarios) VALUES ('00000000A',5,3,50);
INSERT INTO Horarios (dni_profesor_horarios,id_dia_horarios,id_tramo_horarios,id_grupo_horarios,id_asignatura_horarios,id_aula) VALUES ('00000000A',5,7,28,76,42);
