INSERT INTO Profesores (dni, nombre, apellidos, email, puntos_guardia, perfil) VALUES
('P001', 'Enrique', 'del Rosal', 'enrique.delrosal@iesciudadjardin.com', 0, 'Profesorado'),
('P002', 'Irene', 'Merlini', 'irene.merlini@iesciudadjardin.com', 0, 'Profesorado'),
('P003', 'Álvaro', 'Sánchez', 'alvaro.sanchez@iesciudadjardin.com', 0, 'Profesorado'),
('P004', 'Macarena', 'Bermejo', 'macarena.bermejo@iesciudadjardin.com', 0, 'Profesorado'),
('P005', 'Mª Teresa', 'Martín', 'mteresa.martin@iesciudadjardin.com', 0, 'Profesorado'),
('P006', 'Mª Teresa', 'García', 'mteresa.garcia@iesciudadjardin.com', 0, 'Profesorado'),
('P007', 'Isabel', 'Rodríguez', 'isabel.rodriguez@iesciudadjardin.com', 0, 'Profesorado'),
('P008', 'Loreto', 'Alonso', 'loreto.alonso@iesciudadjardin.com', 0, 'Profesorado'),
('P009', 'José Luis', 'León', 'joseluis.leon@iesciudadjardin.com', 0, 'Profesorado'),
('P010', 'Mercedes', 'Barroso', 'mercedes.barroso@iesciudadjardin.com', 0, 'Profesorado'),
('P011', 'Inmaculada', 'Almagro', 'inmaculada.almagro@iesciudadjardin.com', 0, 'Profesorado'),
('P012', 'Amparo', 'Grosso', 'amparo.grosso@iesciudadjardin.com', 0, 'Profesorado'),
('P013', 'Gema', 'Moreno Nobil', 'gema.moreno@iesciudadjardin.com', 0, 'Profesorado'),
('P014', 'Pilar', 'Sierra', 'pilar.sierra@iesciudadjardin.com', 0, 'Profesorado'),
('P015', 'Guillermo', 'Cortés', 'guillermo.cortes@iesciudadjardin.com', 0, 'Profesorado'),
('P016', 'Ignacio', 'Pavón Flores', 'ignacio.pavon@iesciudadjardin.com', 0, 'Profesorado'),
('P017', 'Mª Carmen', 'García', 'mcarmen.garcia@iesciudadjardin.com', 0, 'Profesorado'),
('P018', 'Pastora', 'López', 'pastora.lopez@iesciudadjardin.com', 0, 'Profesorado'),
('P019', 'Rachel', 'Freeman', 'rachel.freeman@iesciudadjardin.com', 0, 'Profesorado'),
('P020', 'Noelia', 'Moreno', 'noelia.moreno@iesciudadjardin.com', 0, 'Profesorado'),
('P021', 'Julio', 'Bermejo', 'julio.bermejo@iesciudadjardin.com', 0, 'Profesorado'),
('P022', 'Cristina', 'Carrascoso', 'cristina.carrascoso@iesciudadjardin.com', 0, 'Profesorado'),
('P023', 'Juan Carlos', 'Canca', 'juancarlos.canca@iesciudadjardin.com', 0, 'Profesorado'),
('P024', 'Juana', 'Escamilla', 'juana.escamilla@iesciudadjardin.com', 0, 'Profesorado'),
('P025', 'Reyes', 'Colomé', 'reyes.colome@iesciudadjardin.com', 0, 'Profesorado'),
('P026', 'Juan Antonio', 'Vadillo', 'juanantonio.vadillo@iesciudadjardin.com', 0, 'Profesorado'),
('P027', 'María del Mar', 'Godoy', 'mariadelmar.godoy@iesciudadjardin.com', 0, 'Profesorado'),
('P028', 'José Antonio', 'Cienfuegos', 'joseantonio.cienfuegos@iesciudadjardin.com', 0, 'Profesorado'),
('P029', 'María', 'Rodríguez', 'maria.rodriguez@iesciudadjardin.com', 0, 'Profesorado'),
('P030', 'Jaime', 'Cordones', 'jaime.cordones@iesciudadjardin.com', 0, 'Profesorado'),
('P031', 'Daniel', 'Fernández', 'daniel.fernandez@iesciudadjardin.com', 0, 'Profesorado'),
('P032', 'Elena', 'de la Hoz', 'elena.delahoz@iesciudadjardin.com', 0, 'Profesorado'),
('P033', 'Salomé', 'Guzmán', 'salome.guzman@iesciudadjardin.com', 0, 'Profesorado'),
('P034', 'Pilar', 'Magariño', 'pilar.magariño@iesciudadjardin.com', 0, 'Profesorado'),
('P035', 'Rafael', 'Díaz Ortiz', 'rafael.diaz@iesciudadjardin.com', 0, 'Profesorado'),
('P036', 'Juan Carlos', 'Cubiles', 'juancarlos.cubiles@iesciudadjardin.com', 0, 'Profesorado'),
('P037', 'Azahara', 'Yago', 'azahara.yago@iesciudadjardin.com', 0, 'Profesorado'),
('P038', 'Mª José', 'Fernández', 'mjose.fernandez@iesciudadjardin.com', 0, 'Profesorado'),
('P039', 'Diego', 'Núñez', 'diego.nunez@iesciudadjardin.com', 0, 'Profesorado');

